task3/config/routes.rb
Rails.application.routes.draw do
  root "numbers#index"
  resources :numbers
end

task3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

task3/app/models/number.rb
class Number < ApplicationRecord
  validates :to_factorial, presence: true, uniqueness: true, length: { maximum: 2 }, numericality: { only_integer: true }
  
  before_save { |number| number.factorialed = _factorial(number.to_factorial, 1) }

  private

  def _factorial(number, value)
    if number < 2
      value
    else
      number * _factorial(number - 1, 1)
    end
  end
  
end

task3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

task3/app/controllers/numbers_controller.rb
class NumbersController < ApplicationController

  def index
    @numbers = Number.all
  end

  def new
    @number = Number.new
  end
  
  def create
    @number = Number.create(number_params)
    if @number.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  private 

  def number_params
    params.require(:number).permit(:to_factorial, :factorialed)
  end
  
  
end

task3/app/helpers/application_helper.rb
module ApplicationHelper
end

task3/app/helpers/numbers_helper.rb
module NumbersHelper
end

task3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

task3/app/views/numbers/index.html.erb
<h1>Factorials</h1>

<h2><%= link_to "New Number", new_number_path %></h2>
<br />

<% @numbers.each do |number| %>
  <div>
    <h3><%= "#{number.to_factorial} - #{number.factorialed}" %></h3>
<% end %>

task3/app/views/numbers/new.html.erb
<h1>Add a number to factorial<h1>

<%= simple_form_for @number do |f| %>
  <%= f.input :to_factorial %>
  <%= f.button :submit %>
<% end %>